# Generated by Django 5.1.4 on 2026-03-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'title'), name='unique_contentitem_source_title')],
            },
        ),
    ]
